question_data = [
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "The Neanderthals were a direct ancestor of modern humans.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "medium",
         "question": "The two atomic bombs dropped on Japan by the United States in August 1945 were named "
                     "&#039;Little Man&#039; and &#039;Fat Boy&#039;.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "Kangaroos keep food in their pouches next to their children.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                          "question": "The sum of all the numbers on a roulette wheel is 666.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "medium",
         "question": "The Southeast Asian island of Borneo is politically divided among 3 countries.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Skateboarding will be included in the 2020 Summer Olympics in Tokyo.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "easy",
          "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
          "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to "
                      "simulate the blood in the famous shower scene from ",
          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "A Saxophone is a brass instrument.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium", "question": "E = MC3",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
         "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
         "question": "&quot;PAYDAY: The Heist&quot; is a sequel to the board game &quot;Payday&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "Daft Punk originated in France.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Pok&eacute;mon, Arbok evolves into Seviper.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
         "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives "
                     "to evaluate limits with indeterminations.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
         "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
         "question": "The song Scatman&#039;s World was released after Scatman (Ski-Ba-Bop-Ba-Dop-Bop).",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Cartoon & Animations", "type": "boolean", "difficulty": "medium",
         "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby&#039;"
                     "s All-Star Laff-a-Lympics.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on "
                     "the streets of Chicago.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
         "question": "Shub-Niggurath is a creature that was created by J. R. R. Tolkien in his novel &quot;"
                     "The Lord of The Rings&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]}
]
